#!/bin/bash

cd $(dirname $0)/..

gangabossdir=`pwd`

echo "Current Ganga directory is $gangabossdir"

refdir="$gangabossdir/../1.0.7"

cd $refdir
reffulldir=`pwd`

echo "Reference Ganga directory is $reffulldir"


cd $gangabossdir

ln -s "$reffulldir/install/5.6.2/bin" install/5.6.2
cp -r "$reffulldir/install/5.6.2/python/Ganga" install/5.6.2/python
ln -s "$reffulldir/external" .
