setenv DIRACPLAT `$DIRAC_INSTALL_PATH/scripts/dirac-platform`

setenv LD_LIBRARY_PATH $DIRAC_INSTALL_PATH/$DIRACPLAT/lib:$LD_LIBRARY_PATH
setenv PATH $DIRAC_INSTALL_PATH/scripts:$DIRAC_INSTALL_PATH/$DIRACPLAT/bin:$PATH
setenv PYTHONPATH ${DIRAC_INSTALL_PATH}:$PYTHONPATH
